# Generated by Django 5.0.1 on 2024-01-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergency_contacts",
                to="employee.emergencycontact",
            ),
        ),
    ]
