# Generated by Django 5.0.1 on 2024-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_emergency_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_time",
            field=models.CharField(max_length=5),
        ),
    ]
