# Generated by Django 5.0.1 on 2024-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_shift_end_time_alter_shift_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="clock_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
