# Generated by Django 5.0.1 on 2024-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_alter_attendance_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(unique=True),
        ),
    ]
