# Generated by Django 5.0.1 on 2024-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_leaverequest_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(),
        ),
    ]
