# Generated by Django 5.0.1 on 2024-01-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_leaverequest_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveapproval",
            name="employee",
        ),
        migrations.AddField(
            model_name="leaveapproval",
            name="leave_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.leaverequest",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaveapproval",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
