# Generated by Django 5.0.1 on 2024-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_remove_leaveapproval_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapproval",
            name="leave_status",
            field=models.CharField(
                choices=[("Approved", "Approved"), ("Rejected", "Rejected")],
                max_length=10,
            ),
        ),
    ]
