# Generated by Django 5.0.1 on 2024-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_leaveapproval_leave_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaverequest",
            old_name="reason",
            new_name="leave_reason",
        ),
        migrations.RemoveField(
            model_name="leaveapproval",
            name="note",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="leaveapproval",
            name="leave_status_note",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_status",
            field=models.CharField(default="Pending"),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_status_note",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
