# Generated by Django 5.0.1 on 2024-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0012_rename_reason_leaverequest_leave_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapproval",
            name="leave_status_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_status_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
