# Generated by Django 5.0.1 on 2024-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="StockItem",
        ),
    ]
