# Generated by Django 5.0.1 on 2024-01-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_rename_product_stockitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
