# Generated by Django 5.0.1 on 2024-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_purchaseorder_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storerequest",
            name="collection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
