# Generated by Django 5.0.1 on 2024-01-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_storerequest_collection_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storerequest",
            name="collected_by",
        ),
    ]
