# Generated by Django 5.0.1 on 2024-01-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_storerequest_requested_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storerequest",
            name="requested_products",
        ),
        migrations.AddField(
            model_name="storerequestitem",
            name="requested_products",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.storerequest",
            ),
            preserve_default=False,
        ),
    ]
