# Generated by Django 5.0.1 on 2024-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_storerequest_requested_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storerequestitem",
            name="requested_products",
        ),
    ]
