# Generated by Django 5.0.1 on 2024-01-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_storerequestitem_requested_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storerequest",
            name="requested_products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.storerequestitem",
            ),
        ),
    ]
