# Generated by Django 5.0.1 on 2024-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_storerequest_requested_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storerequest",
            name="requested_products",
        ),
        migrations.AddField(
            model_name="storerequest",
            name="requested_products",
            field=models.ManyToManyField(to="inventory.storerequestitem"),
        ),
    ]
