# Generated by Django 5.0.1 on 2024-01-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_alter_leaveapproval_leave_status_note_and_more"),
        ("inventory", "0012_remove_storerequest_requested_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storerequest",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_collected_by",
                to="employee.employee",
            ),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_requestedby",
                to="employee.employee",
            ),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="store_request_status",
            field=models.CharField(default="New", max_length=20),
        ),
    ]
