# Generated by Django 5.0.1 on 2024-01-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_storerequest_collected_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasereturnitem",
            old_name="purchase_items",
            new_name="purchase_item",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="purchasereturnitem",
            name="supplier",
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
