# Generated by Django 5.0.1 on 2024-01-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0014_rename_purchase_items_purchasereturnitem_purchase_item_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasereturnitem",
            name="purchase_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_return_item",
                to="inventory.purchaseorderitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturnitem",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturnitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
