# Generated by Django 5.0.1 on 2024-01-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_purchasereturnitem_purchase_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasereturn",
            name="returned_items",
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="returned_items",
            field=models.ManyToManyField(to="inventory.purchasereturnitem"),
        ),
    ]
