# Generated by Django 5.0.1 on 2024-01-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_purchasereturn_returned_items_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storerequest",
            name="requested_products",
        ),
        migrations.AddField(
            model_name="storerequestitem",
            name="store_request",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="StoreRequestItem",
                to="inventory.storerequest",
            ),
            preserve_default=False,
        ),
    ]
