# Generated by Django 5.0.1 on 2024-01-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_remove_storerequest_requested_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storerequest",
            name="store_request_status",
            field=models.CharField(
                choices=[("New", "New"), ("Approved", "Approved")],
                default="New",
                max_length=20,
            ),
        ),
    ]
