# Generated by Django 5.0.1 on 2024-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_otp"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
